# Generated by Django 4.2.4 on 2023-09-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shaadi", "0004_alter_hobby_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="hobbies",
            field=models.ManyToManyField(related_name="profiles", to="shaadi.hobby"),
        ),
    ]
