# Generated by Django 4.2.4 on 2023-08-27 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shaadi", "0003_profile_sect"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hobby",
            options={"verbose_name_plural": "hobbies"},
        ),
    ]
